name: README build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'dark_mode.svg'
      - 'light_mode.svg'
      - 'README.md'
      - 'CURRENT_README.MD'
      - 'cache/**'
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

concurrency:
  group: readme-build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Update README file
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: python3 today.py

      - name: Commit
        run: |-
          git add dark_mode.svg light_mode.svg cache
          git diff --cached --quiet && exit 0
          git diff --cached
          git config --global user.email "github-actions-bot@darkguyaiman.github.io"
          git config --global user.name "Darkguyaiman/GitHub-Actions-Bot"
          git commit -m "Updated README"
          git push
